version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
  build:
    commands:
      - pip install -r requirements.txt -t .
      - zip -r deployment.zip .
  post_build:
    commands:
      - aws lambda update-function-code --function-name EquipmentTelemetry-Backend --zip-file fileb://deployment.zip